apiVersion: v1
kind: Namespace
metadata:
  name: bitcoin-rate-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bitcoin-rate-namespace
  name: bitcoin-rate-service
  labels:
    app: bitcoin-rate-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitcoin-rate-deployment
  template:
    metadata:
      labels:
        app: bitcoin-rate-deployment
    spec:
      containers:
      - name: bitcoin-rate-deployment
        image: bitcoin-rate-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080     
---
apiVersion: v1
kind: Service
metadata:
  namespace: bitcoin-rate-namespace
  name: bitcoin-rate-service
  
spec:
  selector:
    app: bitcoin-rate-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: bitcoin-rate-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: default
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bitcoin-rate-service
            port:
              number: 80